### PR TITLE
fixing the file location in the spec

### PR DESCRIPTION
**Pull request by csyversen**
this is a really small change. We had to update the 'fixture' that we're comparing against. We had the incorrect value before, the file path fragment is what Images is expecting

### CODE REVIEW

**Comment by egspoony** [comment]
Line 25 is an error. 'o' was removed from the end, it should read 'do'.

**Comment by csyversen** [comment]
here don't worry i'll fix it

**Comment by csyversen** [comment]
fixed the 'error'

**Comment by bmquinn** [comment]
I'm on it.

**Pull request merged**
