### PR TITLE
Clean tests

### PR DESCRIPTION
**Pull request by csyversen**
removed tests that are old and misleading! I also removed some unused views too!

### CODE REVIEW

**Comment by jenlindner** [comment]
okay! checking this out too

**Comment by egspoony** [comment]
Should probably merge the other PR first. We haven't done a good job of attempting to close them in order.

**Comment by csyversen** [comment]
it shouldnt' really matter unless we've been overwriting each others code, which i don't think has been happening

**Comment by egspoony** [comment]
Might have on this PR!

**Comment by csyversen** [comment]
i think we'll be ok!!!

**Comment by jenlindner** [comment]
i pulled in the upstream changes, it's cool

**Pull request merged**
